projects = {'dino': ['dinosaurs', 'Wikipedia:WikiProject Dinosaurs/Popular pages'],
	'bird': ['bird', 'Wikipedia:WikiProject Birds/Popular pages'],
	'nrhp': ['National Register of Historic Places', 'Wikipedia:WikiProject National Register of Historic Places/Popular pages'],
	'av': ['aviation', 'Wikipedia:WikiProject Aviation/Popular pages'],
	'ohio': ['Ohio', 'Wikipedia:WikiProject Ohio/Popular pages'],
	'utsh': ['Utah road transport', 'Wikipedia:WikiProject Utah State Highways/Popular pages'],
	'wpmi': ['Michigan', 'Wikipedia:WikiProject Michigan/Popular pages'],
	'pal': ['Palaeontology', 'Wikipedia:WikiProject Palaeontology/Popular pages'],
	'guns': ['Firearms', 'Wikipedia:WikiProject Firearms/Popular pages'],
}