projects = {'dino': ['dinosaurs', 'Wikipedia:WikiProject Dinosaurs/Popular pages'],
	'bird': ['bird', 'Wikipedia:WikiProject Birds/Popular pages'],
	'nrhp': ['National Register of Historic Places', 'Wikipedia:WikiProject National Register of Historic Places/Popular pages'],
	'av': ['aviation', 'Wikipedia:WikiProject Aviation/Popular pages'],
	'ohio': ['Ohio', 'Wikipedia:WikiProject Ohio/Popular pages'],
	'utsh': ['Utah road transport', 'Wikipedia:WikiProject Utah State Highways/Popular pages'],
	'wpmi': ['Michigan', 'Wikipedia:WikiProject Michigan/Popular pages'],
	'pal': ['Palaeontology', 'Wikipedia:WikiProject Palaeontology/Popular pages'],
	'guns': ['Firearms', 'Wikipedia:WikiProject Firearms/Popular pages'],
	'astro': ['Astronomy', 'Wikipedia:WikiProject Astronomy/Popular pages'],
	'dnd': ['Dungeons & Dragons', 'Wikipedia:WikiProject Dungeons & Dragons/Article hits'],
	'beat': ['The Beatles', 'Wikipedia:WikiProject The Beatles/Popular pages'],
	'solar': ['Solar System', 'Wikipedia:WikiProject Solar System/Popular pages'],
	'astobj': ['Astronomical Objects', 'Wikipedia:WikiProject Astronomical objects/Popular pages'],	
	'milhist': ['military history', 'WikiProject Military history/Popular pages'],
	'afrmil': ['African military history', 'Wikipedia:WikiProject Military history/African military history task force/Popular pages'],
	'ausmil': ['Australian military history', 'Wikipedia:WikiProject Military history/Australian military history task force/Popular pages'],
	'balkmil': ['Balkan military history', 'Wikipedia:WikiProject Military history/Balkan military history task force/Popular pages'],
	'balsmil': ['Baltic states military history', 'Wikipedia:WikiProject Military history/Baltic states military history task force/Popular pages'],
	'britmil': ['British military history', 'Wikipedia:WikiProject Military history/British military history task force/Popular pages'],
	'canmil': ['Canadian military history', 'Wikipedia:WikiProject Military history/Canadian military history task force/Popular pages'],
	'chmil': ['Chinese military history', 'Wikipedia:WikiProject Military history/Chinese military history task force/Popular pages'],
	'nlmil': ['Dutch military history', 'Wikipedia:WikiProject Military history/Dutch military history task force/Popular pages'],
	'frmil': ['French military history', 'Wikipedia:WikiProject Military history/French military history task force/Popular pages'],
	'germil': ['German military history', 'Wikipedia:WikiProject Military history/German military history task force/Popular pages'],
	'inmil': ['Indian military history', 'Wikipedia:WikiProject Military history/Indian military history task force/Popular pages'],
	'itmil': ['Italian military history', 'Wikipedia:WikiProject Military history/Italian military history task force/Popular pages'],
	'jamil': ['Japanese military history', 'Wikipedia:WikiProject Military history/Japanese military history task force/Popular pages'],
	'komil': ['Korean military history', 'Wikipedia:WikiProject Korea/Military history/Popular pages'],
	'lebmil': ['Lebanese military history', 'Wikipedia:WikiProject Military history/Lebanese military history task force/Popular pages'],
	'midemil': ['Middle Eastern military history', 'Wikipedia:WikiProject Military history/Middle Eastern military history task force/Popular pages'],
	'nzmil': ['New Zealand military history', 'Wikipedia:WikiProject Military history/New Zealand military history task force/Popular pages'],
	'normil': ['Nordic military history', 'Wikipedia:WikiProject Military history/Nordic military history task force/Popular pages'],
	'ottmil': ['Ottoman military history', 'Wikipedia:WikiProject Military history/Ottoman military history task force/Popular pages'],
	'polmil': ['Polish military history', 'Wikipedia:WikiProject Military history/Polish military history task force/Popular pages'],
	'rommil': ['Romanian military history', 'Wikipedia:WikiProject Military history/Romanian military history task force/Popular pages'],
	'rumil': ['Russian and Soviet military history', 'Wikipedia:WikiProject Military history/Russian and Soviet military history task force/Popular pages'],
	'samil': ['South American military history', 'Wikipedia:WikiProject Military history/South American military history task force/Popular pages'],
	'seamil': ['Southeast Asian military history', 'Wikipedia:WikiProject Military history/Southeast Asian military history task force/Popular pages'],
	'spmil': ['Spanish military history', 'Wikipedia:WikiProject Military history/Spanish military history task force/Popular pages'],
	'tawmil': ['Taiwanese military history', 'Wikipedia:WikiProject Military history/Taiwanese military history task force/Popular pages'],
	'usmil': ['United States military history', 'Wikipedia:WikiProject Military history/United States military history task force/Popular pages'],
	'fort': ['fortifications', 'Wikipedia:WikiProject Military history/Fortifications task force/Popular pages'],
	'intel': ['intelligence', 'Wikipedia:WikiProject Military history/Intelligence task force/Popular pages'],
	'marwar': ['maritime warfare', 'Wikipedia:WikiProject Military history/Maritime warfare task force/Popular pages'],
	'milav': ['military aviation', 'Wikipedia:WikiProject Military history/Military aviation task force/Popular pages'],
	'milhisto': ['biography (military)', 'Wikipedia:WikiProject Biography/Military/Popular pages'],
	'milhisto': ['military historiography', 'Wikipedia:WikiProject Military history/Military historiography task force/Popular pages'],
	'millnd': ['military land vehicles', 'Wikipedia:WikiProject Military history/Military land vehicles task force/Popular pages'],
	'milmem': ['military memorials and cemeteries', 'Wikipedia:WikiProject Military history/Military memorials and cemeteries task force'],
	'milsci': ['military science', 'Wikipedia:WikiProject Military history/Military science task force/Popular pages'],
	'milltech': ['military technology and engineering', 'Wikipedia:WikiProject Military history/Military technology and engineering task force/Popular pages'],
	'milsci': ['national militaries', 'Wikipedia:WikiProject Military history/National militaries task force/Popular pages'],
	'warfilm': ['war films', 'Wikipedia:WikiProject Films/War films task force/Popular pages'],
	'weap': ['weaponry', 'Wikipedia:WikiProject Military history/Weaponry task force/Popular pages'],
	'clswar': ['Classical warfare', 'Wikipedia:WikiProject Military history/Classical warfare task force/Popular pages'],
	'emuswar': ['early Muslim military history', 'Wikipedia:WikiProject Military history/Early Muslim military history task force/Popular pages'],
	'crusade': ['Crusades', 'Wikipedia:WikiProject Middle Ages/Crusades task force/Popular pages'],
	'emodwar': ['Early Modern warfare', 'Wikipedia:WikiProject Military history/Early Modern warfare task force/Popular pages'],
	'amrevwar': ['American Revolutionary War', 'Wikipedia:WikiProject Military history/American Revolutionary War task force/Popular pages'],
	'napol': ['Napoleonic era', 'Wikipedia:WikiProject Military history/Napoleonic era task force/Popular pages'],
	'amcivwar': ['American Civil War', 'Wikipedia:WikiProject Military history/American Civil War task force'],
	'wwi': ['World War I', 'Wikipedia:WikiProject Military history/World War I task force/Popular pages'],
	'wwii': ['World War II', 'Wikipedia:WikiProject Military history/World War II task force/Popular pages'],
	'ships': ['Ships', 'Wikipedia:WikiProject Ships/Popular pages'],
}