projects = {'dino': ['dinosaurs', 'Wikipedia:WikiProject Dinosaurs/Popular pages'],
	'bird': ['bird', 'Wikipedia:WikiProject Birds/Popular pages'],
	'nrhp': ['National Register of Historic Places', 'Wikipedia:WikiProject National Register of Historic Places/Popular pages'],
	'av': ['aviation', 'Wikipedia:WikiProject Aviation/Popular pages'],
	'ohio': ['Ohio', 'Wikipedia:WikiProject Ohio/Popular pages'],
	'utsh': ['Utah road transport', 'Wikipedia:WikiProject Utah State Highways/Popular pages'],
	'wpmi': ['Michigan', 'Wikipedia:WikiProject Michigan/Popular pages'],
	'pal': ['Palaeontology', 'Wikipedia:WikiProject Palaeontology/Popular pages'],
	'guns': ['Firearms', 'Wikipedia:WikiProject Firearms/Popular pages'],
	'astro': ['Astronomy', 'Wikipedia:WikiProject Astronomy/Popular pages'],
	'dnd': ['Dungeons & Dragons', 'Wikipedia:WikiProject Dungeons & Dragons/Article hits'],
	'beat': ['The Beatles', 'Wikipedia:WikiProject The Beatles/Popular pages'],
	'solar': ['Solar System', 'Wikipedia:WikiProject Solar System/Popular pages'],
	'astobj': ['Astronomical Objects', 'Wikipedia:WikiProject Astronomical objects/Popular pages'],
}